service: it-audit-backlog
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    BACKLOG_API_KEY: ${file(./variables.yml):BACKLOG_API_KEY} # 本番用API Key作成後用変更
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - lambda:InvokeFunction
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DeleteNetworkInterface'
      Resource:
        {
          'Fn::Join':
            ['', ['arn:aws:s3:::', { 'Ref': 'ServerlessDeploymentBucket' }]],
        }
functions:
  processing_to_processed: # TODO: 本番適用時、関数名を変える
    handler: handler.update_backlog
    vpc:
      securityGroupIds:
        - sg-0cfa33f10c411fdc1 # TODO: VPC作成後要変更
      subnetIds:
        - subnet-0dc7f4f208edc9c8d # TODO: VPC作成後要変更 / Private Subnet Id のみ
    events:
      - sns:
          topicName: processing_to_processed
          displayName: backlog
