service: it-audit-backlog # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
functions:
  processing_to_processed:
    handler: handler.processing_to_processed
    events:
     - sns:
         topicName: processing_to_processed
         displayName: backlog
