package:
  excludeDevDependencies: false
service: it-audit-backlog-tokinaga
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    BACKLOG_API_KEY: ${file(./variables.yml):BACKLOG_API_KEY}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - lambda:InvokeFunction
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DeleteNetworkInterface'
      Resource:
        {
          'Fn::Join':
            ['', ['arn:aws:s3:::', { 'Ref': 'ServerlessDeploymentBucket' }]],
        }
functions:
  processing_to_processed: # TODO: 本番適用時、関数名を変える
    handler: handler.update_backlog
    events:
      - sns:
          topicName: processing_to_processed-tokinaga
          displayName: backlog-tokinaga
custom:
  defaultStage: dev
  profiles:
    dev: sample
